### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TienIC** [RedstoneAlmeida/MurderMCPE#1]
import cn.nukkit.level.sound.ClickSound;

**Comment by TienIC** [comment]
import cn.nukkit.level.sound.ClickSound;

I have to delete it

ClickSound

Worst of all, NukkitX has reversed everything. You should delete it or add also, even when it is not eaten

**Comment by marcosvkp** [comment]
1.2 Version from NUKKITX, this oldest.

**Comment by marcosvkp** [comment]
As it is an old version, if you want to use it in new versions you will have to update

**Comment by TienIC** [comment]
So you based on the code of Gsound 4.0 is not? I hear it

**Comment by TienIC** [comment]
Take a look at Gsound code

**Comment by TienIC** [comment]
Sorry if my words are not correct due to google translations

**Comment by marcosvkp** [comment]
Not is based, in actually GSound 4.0

**Comment by TienIC** [comment]
No, I mean you should rely on it

**Comment by TienIC** [comment]
Google translates, it is unstable

**Comment by marcosvkp** [comment]
This plugin is incomplete, and also uses the old SOUND method

**Comment by TienIC** [comment]
It's great, I support you
